Some updates for scripts

diff --git a/scripts/compver b/scripts/compver
--- a/scripts/compver
+++ b/scripts/compver
@@ -1,7 +1,8 @@
 #!/bin/bash
-. /lib/lsb/init-functions
 
-package=$1
+init() {
+
+[ ! -d $package ] && echo -e "\n${FAILURE}Your arg is not a package folder${NORMAL}" && exit 1
 
 . $package/Pkgfile
 
@@ -25,6 +26,10 @@ case $package in
 	;;
 esac
 
+search
+}
+
+search() {
 echo -e "\n${SUCCESS}$archpackage search in progress${NORMAL}"
 
 curl -s https://git.archlinux.org/svntogit/community.git/plain/trunk/PKGBUILD?h=packages/$archpackage --output /tmp/$archpackage
@@ -46,9 +51,10 @@ rm /tmp/$archpackage > /dev/null 2>&1
 archversion=$pkgver
 
 rm /tmp/$archpackage > /dev/null 2>&1
+test
+}
 
-
-
+test() {
 if [ -z "$archversion" ]
 	then
 		echo -e "\n${WARNING}The $archpackage package is not in Archlinux Distro,\n or with an another name.We don't take care of this one${NORMAL}"
@@ -60,12 +66,12 @@ fi
 if [ $yaover != $archver ]
 	then
 
-		echo -e "\n${WARNING}Paquet Yao $package à mettre à jour, $yaover vs $archver chez Arch${NORMAL}"
-		echo -e "\n${INFO}Voulez vous mettre à jour la version du Pkgfile $package ?${NORMAL}"
+		echo -e "\n${WARNING}Yao package $package need update, $yaover vs $archver in Arch${NORMAL}"
+		echo -e "\n${INFO}Do you want to update the Pkgfile version $package ?${NORMAL}"
 
 		read a
 
-		case $a in 
+		case $a in
 			y|Y|o|O)
 				sed -e "s/version=${yaover}/version=${archver}/" -i $package/Pkgfile
 
@@ -74,22 +80,6 @@ if [ $yaover != $archver ]
 					then
 						echo -e "\n${SUCCESS}Changes are made${NORMAL}"
 
-						echo -e "\n${INFO}Commit y/n ?${NORMAL}"
-						read b
-
-						case $b in
-							y|Y|o|O)
-								commit $package
-							;;
-
-							n|N)
-								echo -e "\n${INFO} No commit here${NORMAL}"
-							;;
-
-							*)
-								echo -e "\n${INFO}You will commit later${NORMAL}"
-							;;
-						esac
 					else
 						echo -e "\n${FAILURE}Aborting script, changes are not made${NORMAL}"
 						exit 1
@@ -110,5 +100,14 @@ if [ $yaover != $archver ]
 			;;
 		esac
 fi
+}
 
-echo -e "\n${INFO}Don't forget to 'git push'${NORMAL}"
+main() {
+. /lib/lsb/init-functions
+
+package=$1
+
+init $@
+}
+
+main $@
diff --git a/scripts/create-pkg b/scripts/create-pkg
--- a/scripts/create-pkg
+++ b/scripts/create-pkg
@@ -2,7 +2,7 @@
 
 [ $PWD != $HOME ] && echo -e "You're not in your $HOME folder" && exit 1
 
-[ ! -f Pkgfile.example ] && echo -e "Can not find Pkgfile.example, the template file for making a Pkgfile for your package" && exit 1
+[ ! -f $HOME/Pkgfile.example ] && echo -e "Can not find Pkgfile.example, the template file for making a Pkgfile for your package" && exit 1
 
 if [ -z $EDITOR ]
 	then
@@ -12,13 +12,15 @@ if [ -z $EDITOR ]
 		case $edit in
 			e3|vi|vim|nano)
 				echo -e "\nOk, thanks"
+				edit=$(which $edit)
 			;;
 			*)
-				echo -e "\nbad choice, aborting..."
+				echo -e "\nBad choice, aborting..."
+				exit 1
 			;;
 		esac
 	else
-		edit=$EDITOR
+		edit=$(which $EDITOR)
 fi
 
 echo -e "\nIn which collection do you want to create your recipe ?\n"
@@ -31,110 +33,110 @@ read package
 
 case $collection in
 	base)
-		[ ! -d $HOME/git/development/base-sysd ] && echo -e "\nYour local git repo is not at the right place or\nyou don't make the git clone before starting the script" && exit 1
-		mkdir -pv $HOME/git/development/base-sysd/$collection/$package/
-		cat Pkgfile.example > $HOME/git/development/base-sysd/$collection/$package/Pkgfile
+		[ ! -d $HOME/base-sysd ] && echo -e "\nYour local git repo is not at the right place or\nyou don't make the git clone before starting the script" && exit 1
+		mkdir -pv $HOME/base-sysd/$collection/$package/
+		cat $HOME/Pkgfile.example > $HOME/base-sysd/$collection/$package/Pkgfile
 		echo -e "Now, finalize the Pkgfile"
 		sleep 3
-		$edit $HOME/git/development/base-sysd/$collection/$package/Pkgfile
+		$edit $HOME/base-sysd/$collection/$package/Pkgfile
 		echo -e "\nYou'll found your Pkgfile here"
-		echo -e "\n $HOME/git/development/base-sysd/$collection/$package/Pkgfile"
+		echo -e "\n $HOME/base-sysd/$collection/$package/Pkgfile"
 		exit 0
 	;;
 
 	cli|gui)
-		[ ! -d $HOME/git/development/core ] && echo -e "\nYour local git repo is not at the right place or\nyou don't make the git clone before starting the script" && exit 1
-		mkdir -pv $HOME/git/development/core/$collection/$package/
-		cat Pkgfile.example > $HOME/git/development/core/$collection/$package/Pkgfile
+		[ ! -d $HOME/core ] && echo -e "\nYour local git repo is not at the right place or\nyou don't make the git clone before starting the script" && exit 1
+		mkdir -pv $HOME/core/$collection/$package/
+		cat $HOME/Pkgfile.example > $HOME/core/$collection/$package/Pkgfile
 		echo -e "Now, finalize the Pkgfile"
                 sleep 3
-                $edit $HOME/git/development/core/$collection/$package/Pkgfile
+                $edit $HOME/core/$collection/$package/Pkgfile
 		echo -e "\nYou'll found your Pkgfile here"
-                echo -e "\n $HOME/git/development/core/$collection/$package/Pkgfile"
+                echo -e "\n $HOME/core/$collection/$package/Pkgfile"
                 exit 0
 	;;
 
 	cli-extra|gui-extra)
-		[ ! -d $HOME/git/development/extra ] && echo -e "\nYour local git repo is not at the right place or\nyou don't make the git clone before starting the script" && exit 1
-		mkdir -pv $HOME/git/development/extra/$collection/$package/
-		cat Pkgfile.example > $HOME/git/development/extra/$collection/$package/Pkgfile
+		[ ! -d $HOME/extra ] && echo -e "\nYour local git repo is not at the right place or\nyou don't make the git clone before starting the script" && exit 1
+		mkdir -pv $HOME/extra/$collection/$package/
+		cat $HOME/Pkgfile.example > $HOME/extra/$collection/$package/Pkgfile
 		echo -e "Now, finalize the Pkgfile"
                 sleep 3
-                $edit $HOME/git/development/extra/$collection/$package/Pkgfile
+                $edit $HOME/extra/$collection/$package/Pkgfile
 		echo -e "\nYou'll found your Pkgfile here"
-                echo -e "\n $HOME/git/development/extra/$collection/$package/Pkgfile"
+                echo -e "\n $HOME/extra/$collection/$package/Pkgfile"
                 exit 0
 	;;
 
 	kde5|kde5-extra)
-		[ ! -d $HOME/git/development/kde5 ] && echo -e "\nYour local git repo is not at the right place or\nyou don't make the git clone before starting the script" && exit 1
-		mkdir -pv $HOME/git/development/kde5/$collection/$package/
-		cat Pkgfile.example > $HOME/git/development/kde5/$collection/$package/Pkgfile
+		[ ! -d $HOME/kde5 ] && echo -e "\nYour local git repo is not at the right place or\nyou don't make the git clone before starting the script" && exit 1
+		mkdir -pv $HOME/kde5/$collection/$package/
+		cat $HOME/Pkgfile.example > $HOME/kde5/$collection/$package/Pkgfile
 		echo -e "Now, finalize the Pkgfile"
                 sleep 3
-                $edit $HOME/git/development/kde5/$collection/$package/Pkgfile
+                $edit $HOME/kde5/$collection/$package/Pkgfile
 		echo -e "\nYou'll found your Pkgfile here"
-                echo -e "\n $HOME/git/development/kde5/$collection/$package/Pkgfile"
+                echo -e "\n $HOME/kde5/$collection/$package/Pkgfile"
                 exit 0
 	;;
 
 	gnome|gnome-extra)
-		[ ! -d $HOME/git/development/kde5 ] && echo -e "\nYour local git repo is not at the right place or\nyou don't make the git clone before starting the script" && exit 1
-		mkdir -pv $HOME/git/development/gnome/$collection/$package/
-		cat Pkgfile.example > $HOME/git/development/gnome/$collection/$package/Pkgfile
+		[ ! -d $HOME/gnome ] && echo -e "\nYour local git repo is not at the right place or\nyou don't make the git clone before starting the script" && exit 1
+		mkdir -pv $HOME/gnome/$collection/$package/
+		cat $HOME/Pkgfile.example > $HOME/gnome/$collection/$package/Pkgfile
 		echo -e "Now, finalize the Pkgfile"
                 sleep 3
-                $edit $HOME/git/development/gnome/$collection/$package/Pkgfile
+                $edit $HOME/gnome/$collection/$package/Pkgfile
 		echo -e "\nYou'll found your Pkgfile here"
-                echo -e "\n $HOME/git/development/gnome/$collection/$package/Pkgfile"
+                echo -e "\n $HOME/gnome/$collection/$package/Pkgfile"
                 exit 0
 	;;
 
 	lxde|lxde-extra)
-		[ ! -d $HOME/git/development/kde5 ] && echo -e "\nYour local git repo is not at the right place or\nyou don't make the git clone before starting the script" && exit 1
-		mkdir -pv $HOME/git/development/lxde/$collection/$package/
-		cat Pkgfile.example > $HOME/git/development/lxde/$collection/$package/Pkgfile
+		[ ! -d $HOME/lxde ] && echo -e "\nYour local git repo is not at the right place or\nyou don't make the git clone before starting the script" && exit 1
+		mkdir -pv $HOME/lxde/$collection/$package/
+		cat $HOME/Pkgfile.example > $HOME/lxde/$collection/$package/Pkgfile
 		echo -e "Now, finalize the Pkgfile"
                 sleep 3
-                $edit $HOME/git/development/lxde/$collection/$package/Pkgfile
+                $edit $HOME/lxde/$collection/$package/Pkgfile
 		echo -e "\nYou'll found your Pkgfile here"
-                echo -e "\n $HOME/git/development/lxde/$collection/$package/Pkgfile"
+                echo -e "\n $HOME/lxde/$collection/$package/Pkgfile"
                 exit 0
 	;;
 
 	xfce4|xfce4-extra)
-		[ ! -d $HOME/git/development/xfce4 ] && echo -e "\nYour local git repo is not at the right place or\nyou don't make the git clone before starting the script" && exit 1
-		mkdir -pv $HOME/git/development/xfce4/$collection/$package/
-		cat Pkgfile.example > $HOME/git/development/xfce4/$collection/$package/Pkgfile
+		[ ! -d $HOME/xfce4 ] && echo -e "\nYour local git repo is not at the right place or\nyou don't make the git clone before starting the script" && exit 1
+		mkdir -pv $HOME/xfce4/$collection/$package/
+		cat $HOME/Pkgfile.example > $HOME/xfce4/$collection/$package/Pkgfile
                 echo -e "Now, finalize the Pkgfile"
                 sleep 3
-                $edit $HOME/git/development/xfce4/$collection/$package/Pkgfile
+                $edit $HOME/xfce4/$collection/$package/Pkgfile
 		echo -e "\nYou'll found your Pkgfile here"
-                echo -e "\n $HOME/git/development/xfce4/$collection/$package/Pkgfile"
+                echo -e "\n $HOME/xfce4/$collection/$package/Pkgfile"
                 exit 0
 	;;
 
 	mate|mate-extra)
-		[ ! -d $HOME/git/development/mate ] && echo -e "\nYour local git repo is not at the right place or\nyou don't make the git clone before starting the script" && exit 1
-		mkdir -pv $HOME/git/development/mate/$collection/$package/
-		cat Pkgfile.example > $HOME/git/development/mate/$collection/$package/Pkgfile
+		[ ! -d $HOME/mate ] && echo -e "\nYour local git repo is not at the right place or\nyou don't make the git clone before starting the script" && exit 1
+		mkdir -pv $HOME/mate/$collection/$package/
+		cat $HOME/Pkgfile.example > $HOME/mate/$collection/$package/Pkgfile
                 echo -e "Now, finalize the Pkgfile"
                 sleep 3
-                $edit $HOME/git/development/mate/$collection/$package/Pkgfile
+                $edit $HOME/mate/$collection/$package/Pkgfile
 		echo -e "\nYou'll found your Pkgfile here"
-                echo -e "\n $HOME/git/development/mate/$collection/$package/Pkgfile"
+                echo -e "\n $HOME/mate/$collection/$package/Pkgfile"
                 exit 0
 	;;
 
 	nos)
-		[ ! -d $HOME/git/development/nos ] && echo -e "\nYour local git repo is not at the right place or\nyou don't make the git clone before starting the script" && exit 1
-		mkdir -pv $HOME/git/development/nos/$collection/$package/
-		cat Pkgfile.example > $HOME/git/development/nos/$collection/$package/Pkgfile
+		[ ! -d $HOME/nos ] && echo -e "\nYour local git repo is not at the right place or\nyou don't make the git clone before starting the script" && exit 1
+		mkdir -pv $HOME/nos/$collection/$package/
+		cat $HOME/Pkgfile.example > $HOME/nos/$collection/$package/Pkgfile
 		echo -e "Now, finalize the Pkgfile"
                 sleep 3
-                $edit $HOME/git/development/nos/$collection/$package/Pkgfile
+                $edit $HOME/nos/$collection/$package/Pkgfile
 		echo -e "\nYou'll found your Pkgfile here"
-                echo -e "\n $HOME/git/development/nos/$collection/$package/Pkgfile"
+                echo -e "\n $HOME/nos/$collection/$package/Pkgfile"
                 exit 0
 	;;
 
